server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/Abel3581/microservis-crud
          search-paths: config-data

  application:
    name: config-service